<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0 static\models\City.gltf -t -u -m
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const suspend = useSuspense()

  type GLTFResult = {
    nodes: {
      House5: THREE.Mesh
      House3: THREE.Mesh
      House2: THREE.Mesh
      RoadCross: THREE.Mesh
      House1: THREE.Mesh
      Foundation002: THREE.Mesh
      RoadStraight005: THREE.Mesh
      RoadTCross003: THREE.Mesh
      RoadCorner: THREE.Mesh
      RoadStraight008: THREE.Mesh
      RoadStraight011: THREE.Mesh
      RoadStraight004: THREE.Mesh
      RoadCorner001: THREE.Mesh
      RoadCorner002: THREE.Mesh
      RoadCorner003: THREE.Mesh
      RoadStraight003: THREE.Mesh
      RoadStraight007: THREE.Mesh
      RoadStraight: THREE.Mesh
      RoadStraight002: THREE.Mesh
      RoadStraight001: THREE.Mesh
      RoadStraight009: THREE.Mesh
      RoadStraight010: THREE.Mesh
      RoadStraight006: THREE.Mesh
      Foundation001: THREE.Mesh
      Foundation003: THREE.Mesh
      Foundation: THREE.Mesh
      RoadTCross002: THREE.Mesh
      RoadTCross001: THREE.Mesh
      RoadTCross: THREE.Mesh
    }
    materials: {
      House: THREE.MeshStandardMaterial
      Road: THREE.MeshStandardMaterial
      Foundation: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>('/models/City.gltf'))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.House5.geometry}
      material={gltf.materials.House}
      position={[25, 0.7, 25]}
      scale={10}
      userData={{ name: 'House5' }}
    />
    <T.Mesh
      geometry={gltf.nodes.House3.geometry}
      material={gltf.materials.House}
      position={[-25, 0.7, -25]}
      scale={10}
      userData={{ name: 'House3' }}
    />
    <T.Mesh
      geometry={gltf.nodes.House2.geometry}
      material={gltf.materials.House}
      position={[25, 0.7, -25]}
      scale={10}
      userData={{ name: 'House2' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadCross.geometry}
      material={gltf.materials.Road}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadCross' }}
    />
    <T.Mesh
      geometry={gltf.nodes.House1.geometry}
      material={gltf.materials.House}
      position={[-25, 0.7, 25]}
      scale={10}
      userData={{ name: 'House1' }}
    />
    <T.Mesh
      geometry={gltf.nodes.Foundation002.geometry}
      material={gltf.materials.Foundation}
      position={[25, -0.85, 25]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'Foundation.002' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight005.geometry}
      material={gltf.materials.Road}
      position={[25, 0, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.005' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadTCross003.geometry}
      material={gltf.materials.Road}
      position={[50, 0, 0]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadTCross.003' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadCorner.geometry}
      material={gltf.materials.Road}
      position={[50, 0, -50]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadCorner' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight008.geometry}
      material={gltf.materials.Road}
      position={[0, 0, 25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.008' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight011.geometry}
      material={gltf.materials.Road}
      position={[0, 0, -25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.011' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight004.geometry}
      material={gltf.materials.Road}
      position={[-25, 0, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.004' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadCorner001.geometry}
      material={gltf.materials.Road}
      position={[50, 0, 50]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadCorner.001' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadCorner002.geometry}
      material={gltf.materials.Road}
      position={[-50, 0, 50]}
      rotation={[0, 1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadCorner.002' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadCorner003.geometry}
      material={gltf.materials.Road}
      position={[-50, 0, -50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadCorner.003' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight003.geometry}
      material={gltf.materials.Road}
      position={[-50, 0, -25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.003' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight007.geometry}
      material={gltf.materials.Road}
      position={[-50, 0, 25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.007' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight.geometry}
      material={gltf.materials.Road}
      position={[50, 0, 25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight002.geometry}
      material={gltf.materials.Road}
      position={[50, 0, -25]}
      rotation={[0, -1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.002' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight001.geometry}
      material={gltf.materials.Road}
      position={[25, 0, -50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.001' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight009.geometry}
      material={gltf.materials.Road}
      position={[25, 0, 50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.009' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight010.geometry}
      material={gltf.materials.Road}
      position={[-25, 0, 50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.010' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadStraight006.geometry}
      material={gltf.materials.Road}
      position={[-25, 0, -50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadStraight.006' }}
    />
    <T.Mesh
      geometry={gltf.nodes.Foundation001.geometry}
      material={gltf.materials.Foundation}
      position={[-25, -0.85, 25]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'Foundation.001' }}
    />
    <T.Mesh
      geometry={gltf.nodes.Foundation003.geometry}
      material={gltf.materials.Foundation}
      position={[25, -0.85, -25]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'Foundation.003' }}
    />
    <T.Mesh
      geometry={gltf.nodes.Foundation.geometry}
      material={gltf.materials.Foundation}
      position={[-25, -0.85, -25]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'Foundation' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadTCross002.geometry}
      material={gltf.materials.Road}
      position={[0, 0, -50]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadTCross.002' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadTCross001.geometry}
      material={gltf.materials.Road}
      position={[-50, 0, 0]}
      rotation={[0, 1.57, 0]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadTCross.001' }}
    />
    <T.Mesh
      geometry={gltf.nodes.RoadTCross.geometry}
      material={gltf.materials.Road}
      position={[0, 0, 50]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[12.5, 0.66, 12.5]}
      userData={{ name: 'RoadTCross' }}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
