<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0 static\models\Firetruck.gltf -t -u -m
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const suspend = useSuspense()

  type ActionName =
    | 'TurnLeft'
    | 'TurnRight'
    | 'BoomRotate'
    | 'BoomLift'
    | 'HeadlightsOn'
    | 'RFlashOn'
    | 'LFlashOn'
    | 'Wiper'
    | 'BoomElbow'
    | 'BoomWrist'
  type GLTFResult = {
    nodes: {
      FlWheel: THREE.Mesh
      FrWheel: THREE.Mesh
      BoomSocket: THREE.Mesh
      BoomShoulder: THREE.Mesh
      BoomElbow: THREE.Mesh
      BoomWrist: THREE.Mesh
      BoomWristWaterGun: THREE.Mesh
      BoomWristWaterGunTip: THREE.Mesh
      HeadlightsOn: THREE.Mesh
      RFlashOn: THREE.Mesh
      LFlashOn: THREE.Mesh
      WiperSocket: THREE.Mesh
      WiperBlade: THREE.Mesh
      Body: THREE.Mesh
      FrontWindow: THREE.Mesh
      HeadlightsOff: THREE.Mesh
      LeftSideWindow: THREE.Mesh
      LFlashOff: THREE.Mesh
      RFlashOff: THREE.Mesh
      RightSideWindow: THREE.Mesh
      RlWheel: THREE.Mesh
      RrWheel: THREE.Mesh
    }
    materials: {
      Tire: THREE.MeshStandardMaterial
      Metal: THREE.MeshStandardMaterial
      Red: THREE.MeshStandardMaterial
      Orange: THREE.MeshStandardMaterial
      HeadlightOn: THREE.MeshStandardMaterial
      FlashOn: THREE.MeshStandardMaterial
      Rubber: THREE.MeshStandardMaterial
      Glass: THREE.MeshStandardMaterial
      LightOff: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>('/models/Firetruck.gltf'))
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Firetruck" userData={{ name: 'Firetruck' }}>
        <T.Group
          name="RearCamera"
          position={[-5.67, 18.13, -33.57]}
          rotation={[1.95, -0.05, 3.08]}
          userData={{ name: 'RearCamera' }}
        />
        <T.Mesh
          name="FlWheel"
          geometry={gltf.nodes.FlWheel.geometry}
          material={gltf.materials.Tire}
          position={[1.5, 0.5, 3.5]}
          userData={{ name: 'FlWheel' }}
        />
        <T.Mesh
          name="FrWheel"
          geometry={gltf.nodes.FrWheel.geometry}
          material={gltf.materials.Tire}
          position={[-1.5, 0.5, 3.5]}
          userData={{ name: 'FrWheel' }}
        />
        <T.Mesh
          name="BoomSocket"
          geometry={gltf.nodes.BoomSocket.geometry}
          material={gltf.materials.Metal}
          position={[0, 3.75, -3.5]}
          userData={{ name: 'BoomSocket' }}
        >
          <T.Mesh
            name="BoomShoulder"
            geometry={gltf.nodes.BoomShoulder.geometry}
            material={gltf.materials.Metal}
            position={[0, 0.57, 0]}
            scale={[1, 0.5, 1]}
            userData={{ name: 'BoomShoulder' }}
          >
            <T.Mesh
              name="BoomElbow"
              geometry={gltf.nodes.BoomElbow.geometry}
              material={gltf.materials.Metal}
              position={[0, 0.6, 9.5]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.75, 0.38, 0.38]}
              userData={{ name: 'BoomElbow' }}
            >
              <T.Mesh
                name="BoomWrist"
                geometry={gltf.nodes.BoomWrist.geometry}
                material={gltf.materials.Metal}
                rotation={[0, 0, Math.PI / 2]}
                scale={2.67}
                userData={{ name: 'BoomWrist' }}
              >
                <T.Mesh
                  name="BoomWristWaterGun"
                  geometry={gltf.nodes.BoomWristWaterGun.geometry}
                  material={gltf.materials.Red}
                  position={[0, 2, 3.65]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.2, 1, 0.2]}
                  userData={{ name: 'BoomWristWaterGun' }}
                >
                  <T.Mesh
                    name="BoomWristWaterGunTip"
                    geometry={gltf.nodes.BoomWristWaterGunTip.geometry}
                    material={gltf.materials.Orange}
                    position={[0, 1, 0]}
                    scale={[0.65, 0.13, 0.65]}
                    userData={{ name: 'BoomWristWaterGunTip' }}
                  />
                </T.Mesh>
              </T.Mesh>
            </T.Mesh>
          </T.Mesh>
        </T.Mesh>
        <T.Mesh
          name="HeadlightsOn"
          geometry={gltf.nodes.HeadlightsOn.geometry}
          material={gltf.materials.HeadlightOn}
          position={[1.15, 0.88, 4.9]}
          userData={{ name: 'HeadlightsOn' }}
        />
        <T.Mesh
          name="RFlashOn"
          geometry={gltf.nodes.RFlashOn.geometry}
          material={gltf.materials.FlashOn}
          position={[1.25, 0.88, 4.9]}
          userData={{ name: 'RFlashOn' }}
        />
        <T.Mesh
          name="LFlashOn"
          geometry={gltf.nodes.LFlashOn.geometry}
          material={gltf.materials.FlashOn}
          position={[1.35, 0.88, 4.9]}
          userData={{ name: 'LFlashOn' }}
        />
        <T.Mesh
          name="WiperSocket"
          geometry={gltf.nodes.WiperSocket.geometry}
          material={gltf.materials.Rubber}
          position={[0, 2.5, 5.09]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.05}
          userData={{ name: 'WiperSocket' }}
        >
          <T.Mesh
            name="WiperBlade"
            geometry={gltf.nodes.WiperBlade.geometry}
            material={gltf.materials.Rubber}
            position={[0, 0.99, 0.14]}
            rotation={[1.71, 0, 0]}
            scale={20}
            userData={{ name: 'WiperBlade' }}
          />
        </T.Mesh>
        <T.Mesh
          name="Body"
          geometry={gltf.nodes.Body.geometry}
          material={gltf.materials.Red}
          userData={{ name: 'Body' }}
        />
        <T.Mesh
          name="FrontWindow"
          geometry={gltf.nodes.FrontWindow.geometry}
          material={gltf.materials.Glass}
          position={[0, 3.13, 5.03]}
          scale={[1.35, 0.75, 0.03]}
          userData={{ name: 'FrontWindow' }}
        />
        <T.Mesh
          name="HeadlightsOff"
          geometry={gltf.nodes.HeadlightsOff.geometry}
          material={gltf.materials.LightOff}
          position={[1.15, 0.88, 5]}
          userData={{ name: 'HeadlightsOff' }}
        />
        <T.Mesh
          name="LeftSideWindow"
          geometry={gltf.nodes.LeftSideWindow.geometry}
          material={gltf.materials.Glass}
          position={[1.52, 3.13, 4.18]}
          rotation={[0, -1.57, 0]}
          scale={[1.35, 0.75, 0.03]}
          userData={{ name: 'LeftSideWindow' }}
        />
        <T.Mesh
          name="LFlashOff"
          geometry={gltf.nodes.LFlashOff.geometry}
          material={gltf.materials.LightOff}
          position={[1.35, 0.88, 5.02]}
          userData={{ name: 'LFlashOff' }}
        />
        <T.Mesh
          name="RFlashOff"
          geometry={gltf.nodes.RFlashOff.geometry}
          material={gltf.materials.LightOff}
          position={[-1.35, 0.88, 5.02]}
          userData={{ name: 'RFlashOff' }}
        />
        <T.Mesh
          name="RightSideWindow"
          geometry={gltf.nodes.RightSideWindow.geometry}
          material={gltf.materials.Glass}
          position={[-1.52, 3.13, 4.9]}
          rotation={[0, -1.57, 0]}
          scale={[1.35, 0.75, 0.03]}
          userData={{ name: 'RightSideWindow' }}
        />
        <T.Mesh
          name="RlWheel"
          geometry={gltf.nodes.RlWheel.geometry}
          material={gltf.materials.Tire}
          position={[1.5, 0.5, -3.5]}
          userData={{ name: 'RlWheel' }}
        />
        <T.Mesh
          name="RrWheel"
          geometry={gltf.nodes.RrWheel.geometry}
          material={gltf.materials.Tire}
          position={[-1.5, 0.5, -3.5]}
          userData={{ name: 'RrWheel' }}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
